color: null
fieldLayouts:
  6f6f33cb-407b-44ee-b46a-fc701a767891:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-07T14:23:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fe6a2c64-206d-4e48-b128-021e07fc200a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: d55f11cd-5d19-4a1d-a318-e6a53750a168 # Accordions
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e087e0b-65fa-44bd-8924-89f9f26082a9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8dfdffe3-9463-4d1e-970f-db01b1cb9276
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a92669dd-1253-4a20-905f-10c28df06b35
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cddcca71-55d7-4757-a751-7ffcdb864833
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 0f5da106-4758-4a32-806f-a95ba43b826b # Sub Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34d73aa1-b113-4e41-bd75-82936612302b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f030b0de-9484-4438-9ec0-8da71f0a3bcd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: b725ddfa-71d5-44fd-b67b-d2291907d5fd # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f07ab7a-bda0-45b2-9afd-71d530037109
            userCondition: null
            warning: null
            width: 100
        name: Auxiliary
        uid: f1e2678a-36b0-4973-acfa-a143077c9a5b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            heading: 'Block Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 83f39667-6a5e-4f8a-9955-0636da785bfb
            userCondition: null
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 4daa21a6-7d9e-4652-b72d-4b86d193b8cd # Content Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da992206-0a61-4b0a-a38c-a7e24880c800
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 5b639435-9f82-4cfa-9b34-0421722361c9 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54b2ea8a-8ed1-4a64-b7b1-c109d0f0b59d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 54a3d4c9-582f-4754-8977-4c342ef8a96e # Overlay Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5cab44f-fac5-4942-9f9a-9ec773c197b0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            heading: 'Content Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 0a6c0d6c-47dc-4461-9dbe-96dcf1a566dd
            userCondition: null
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: f5f3b40a-47d4-42d5-b50a-5e17eae1e600 # Content Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 200f8b43-dd49-4673-8bc0-4e416bf5a9eb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: e38ac257-70df-4d50-9384-503f2133f772 # Heading Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f76346c-9eb2-4f61-8b8d-c9fcbb075754
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 0e6d4e36-9f7c-4320-bfad-dcc290f8e135 # Font Weight
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d7622b0-b68f-430b-9794-6932101e3ac5
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 2f339c20-d253-414a-9cd9-6e9d05ed4d22
            userCondition: null
          -
            dateAdded: '2025-03-03T14:32:35+00:00'
            elementCondition: null
            fieldUid: 2ba320e0-e879-4969-b03c-211b60735a5a # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94048352-1575-43b0-8dda-1a2f22f02c03
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: deb2e377-109e-4466-b393-6922e2ba9455
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 86035a0d-51de-4bb2-b452-4bfc32cfc03e # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90740964-b0f7-42a6-bfdd-ed615ec22d16
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: f4be19c5-ac47-4a53-808f-46357722601c # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79e52cc3-5214-4638-a40f-26f085a356bf
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: c16118bb-d24d-489d-8c5a-2deabdcd6e16 # Padding Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19fdbe06-48e9-4af6-ba33-01c0ffe1486d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: bff0694b-0a96-4afa-ba0e-b4e834e9a153 # Padding Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3150d3d2-b2cd-474e-93bf-3bdcb67fcdd4
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 1549414a-75b6-4624-a738-3071db659acc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: animation
            includeInCards: false
            instructions: null
            label: 'Animation?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 359c563e-e2ae-47a5-8d0c-fa99f811c941
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 50113607-8620-4732-a0a7-5682fcd6ee62
            userCondition: null
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 1d563f74-0673-4d93-9848-cfbf74332e88 # Animation Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93a04081-be87-42ad-85a5-294b9a4bcf84
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: ed742f3d-8fc4-44e1-b975-1b03cb9ab839 # Animation Easing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa70e5cb-bcca-460d-a76a-cfecff1535c2
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 86da9d1c-79b6-4b38-bfe8-d608e36d610c # Animation Duration
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb0bd715-d33d-49c5-a6d0-af06e17d9548
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T14:23:11+00:00'
            elementCondition: null
            fieldUid: 703a980f-eab2-4276-a815-17e7b6f5095a # Animation Offset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 161c504c-4399-469d-9d9f-e62c3567ddd9
            userCondition: null
            warning: null
            width: 50
        name: Animation
        uid: 3ed10396-f47e-4795-a1f2-dc688082d01a
        userCondition: null
handle: accordion
hasTitleField: false
icon: ''
name: Accordion
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
