color: null
fieldLayouts:
  5cf95b83-da41-420d-a6b6-a4ddc7e4e3f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b2608e23-42a6-4ada-9e32-25938c17155e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 340346c4-b49d-4185-a623-2fcabdd6f0ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d02bb5a-92bb-4f87-8e01-8cfd61fbeee1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f5da106-4758-4a32-806f-a95ba43b826b # Sub Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09cafedb-f42a-43f8-b872-3b81bac733a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 786eba8d-bcde-43f6-9cca-4e2e4b5dfb56
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b725ddfa-71d5-44fd-b67b-d2291907d5fd # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0d232b4-17a3-4e36-8520-d78830fcd4b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7fa1dd8c-cc61-4015-919e-819e3c95b345
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4daa21a6-7d9e-4652-b72d-4b86d193b8cd # Content Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c75a129-752a-4d0d-9b53-19475e77ad3c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b639435-9f82-4cfa-9b34-0421722361c9 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37831e46-ea0e-422e-bf41-67a7f671b2fe
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 54a3d4c9-582f-4754-8977-4c342ef8a96e # Overlay Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40b10307-9b01-4b92-bae7-7db733a13d8f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e38ac257-70df-4d50-9384-503f2133f772 # Heading Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58e54d1a-e0b9-4bb3-b1f6-039856eba74b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 0e6d4e36-9f7c-4320-bfad-dcc290f8e135 # Font Weight
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d82a2c4-f732-41bb-8273-7522ea917438
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f5f3b40a-47d4-42d5-b50a-5e17eae1e600 # Content Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 939ec28b-1f2f-4b5d-8770-ff7167746cfe
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0d521dbe-7a8d-4492-bffd-b2cfe50041ba
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2ba320e0-e879-4969-b03c-211b60735a5a # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 837f5756-1d61-4ecf-831b-baf0f8f93144
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 0d397130-f6a8-4af9-930f-327ce8db90f6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 86035a0d-51de-4bb2-b452-4bfc32cfc03e # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75a01875-12a9-4997-8462-53bc606d3411
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f4be19c5-ac47-4a53-808f-46357722601c # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5cd17e3-4864-4950-a581-2ac663e43746
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c16118bb-d24d-489d-8c5a-2deabdcd6e16 # Padding Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 147a7806-8a6d-4ec7-a26a-59828b566048
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bff0694b-0a96-4afa-ba0e-b4e834e9a153 # Padding Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b1ea0fb-968f-44cd-aaae-475fc5d8af0e
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 3f568f7c-4ae2-40a5-b038-429eed951a00
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: animation
            includeInCards: false
            instructions: null
            label: 'Animation?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 900eed46-13a0-46bb-a659-ec243e78877d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 44fdbca2-f086-4320-a4d8-26b21ebf757b
            userCondition: null
          -
            elementCondition: null
            fieldUid: 1d563f74-0673-4d93-9848-cfbf74332e88 # Animation Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 848b76c3-e4c5-4384-a362-81288dc6acf2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ed742f3d-8fc4-44e1-b975-1b03cb9ab839 # Animation Easing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58fb699b-1ad6-47d4-82fd-848b2ee47af3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 86da9d1c-79b6-4b38-bfe8-d608e36d610c # Animation Duration
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe799485-74b4-4754-a207-2a5e9ff9c57b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 703a980f-eab2-4276-a815-17e7b6f5095a # Animation Offset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57cfdf39-ddff-4fd2-bbf4-ecd54d145746
            userCondition: null
            warning: null
            width: 50
        name: Animation
        uid: 216a58a7-ecd5-48ec-8197-b7af46610c31
        userCondition: null
handle: basicContent
hasTitleField: false
icon: ''
name: 'Basic Content'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
