color: null
fieldLayouts:
  65788af3-8c4a-4513-a641-ba9d23fd0d40:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 394fe8fc-f8ff-4937-8c43-9c2fb1e2165b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b55158c-eeaf-42fa-a2a5-630caaf27f7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2faf60a-48de-4391-a3c4-49283f508b99 # Related Team Member
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a470276-1621-4a32-8390-f86d0d5cec4a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8924f8be-b7ee-44cf-991c-9fc458096173 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6559c186-c21d-465d-b5c1-343f5cfb34cf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05c8072a-b060-47e9-9d20-81229d6ada25
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b3c80522-1b2a-44ca-954e-be2e2544ebd9 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f04238b-95aa-4bee-b1cd-c4ba173967cb
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4a338772-68b6-49a3-b90a-790cc39e75e3
        userCondition: null
handle: blog
hasTitleField: true
icon: ''
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
