color: null
fieldLayouts:
  57c30409-ca58-4ec5-9a98-0c440884fb78:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 39eb628c-ec05-40ff-92a5-3d2bcd3df30c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05af4b17-93ed-4027-a039-96c368e5b585 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa79aabf-e81f-4f06-ba38-d194085ea656
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3745cb40-58d5-44cc-9ce5-9339f438f411 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 461d4293-b319-47c2-905b-b6388694b750
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c38f446c-aaa6-48a2-ba95-c6febfc4e575
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ebf7fef-3a0d-407c-9f23-24a7ee8dff54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a98d225b-882f-4969-8e87-de0919a6091e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c8987af-e9f1-42e8-930e-4a16028b925d # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f505e639-ca1b-4602-967a-0b6fd8f050e4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 46478808-5a74-469b-9529-489d69009810
        userCondition: null
handle: card
hasTitleField: false
icon: ''
name: Card
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
