color: null
fieldLayouts:
  3313288a-5156-40da-ae8e-690eee179f08:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ff93fe38-6352-4663-98fd-460e6e230112
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e057613e-4692-4816-9828-dbc13789fc20
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b6c930d-d00e-4a6c-9e5e-734464c5066a # Simple Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e576276e-1cb3-4f5e-83a6-1d4293895343
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a2d1d263-cb95-4bf6-8c25-78940728412d
        userCondition: null
handle: cards
hasTitleField: false
icon: ''
name: Cards
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
