color: null
fieldLayouts:
  c5a3557e-f780-4f94-b816-641c2ccbc38c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-19T09:20:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 77e85c34-0858-43e8-9519-28c521b53739
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T09:20:59+00:00'
            elementCondition: null
            fieldUid: 6343b9b3-faa9-4f99-b112-fdec9bd6d770 # Related Client
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01c56ef3-ea93-4cb2-9268-8c086c79c67f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T09:20:59+00:00'
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96858f43-084a-4b75-9e78-e90db88214b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T09:22:26+00:00'
            elementCondition: null
            fieldUid: 1f8f6d28-a4f1-4472-9791-ecc7e78635b9 # Company Tagline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e423eb81-985c-41c7-a026-bd70ab32b0c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T09:20:59+00:00'
            elementCondition: null
            fieldUid: 8924f8be-b7ee-44cf-991c-9fc458096173 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 080bf9a5-fdac-4a3c-b787-97c56c864f59
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: db08312f-8121-4adb-9df0-8f2ddf016424
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T10:22:40+00:00'
            elementCondition: null
            fieldUid: cc5e2abd-42a9-498e-a6f6-d6596c99d2c5 # Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e9627cc-731e-4c46-b5ae-ec9cef530b65
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T10:22:40+00:00'
            elementCondition: null
            fieldUid: 7e031956-6581-4ca0-8543-f84eca882b06 # Show Case Studies?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3910a265-85e6-4820-b4c4-6f6b6afc0fcb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-19T10:22:40+00:00'
            elementCondition: null
            fieldUid: 19036f8c-8350-455e-a721-9938e3cf9811 # Related Case Study
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c0822ae-8aed-4b31-b40b-644e6a4b936e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-19T12:33:02+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 68102d66-3089-498c-a989-60e64e72ce38
            userCondition: null
          -
            dateAdded: '2025-02-19T12:31:11+00:00'
            elementCondition: null
            fieldUid: 22931d1e-b9cf-4371-84e1-5c465efccf3d # Override CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19cc4823-5a3a-40fc-a009-13ab47f49ce9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-19T12:31:11+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 22931d1e-b9cf-4371-84e1-5c465efccf3d # Override CTA
                  layoutElementUid: 19cc4823-5a3a-40fc-a009-13ab47f49ce9
                  uid: b2d4e072-aeb0-49e9-9875-f9d15a978bf8
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 3103da10-e23c-4bc6-8d50-79ecfca1013e # Call To Action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f5678fc-e338-4fa1-bf6f-83f6f11f7042
            userCondition: null
            warning: null
            width: 50
        name: Meta
        uid: 78a9ce07-6f84-4075-8ea5-a72dfc46ec8b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T09:20:59+00:00'
            elementCondition: null
            fieldUid: b3c80522-1b2a-44ca-954e-be2e2544ebd9 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf4075db-70cb-4544-9c19-a5957949bdec
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 152e7677-38ff-4dc4-b5ab-541950199fc7
        userCondition: null
handle: caseStudy
hasTitleField: true
icon: ''
name: 'Case study'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
