color: null
fieldLayouts:
  40ab32b6-eb91-4a27-8882-57ac33593eeb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 49147769-1ad7-439b-8139-834d073651e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 134a2c99-8e12-4d05-b077-5957f5e835ce # Social Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1a716ce-15d4-4ed4-a44f-e1c45faae0ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4dae96d6-b047-4a61-a804-230fa4a57426
        userCondition: null
handle: contactSocialLinks
hasTitleField: false
icon: icons
name: 'Contact Social Links'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
