color: null
fieldLayouts:
  8663fc8b-ea4f-479b-b576-2466e632f47e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ab7222c5-e311-4b89-a215-26011f262668
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f274f48-4f99-440c-b5fb-c28fa62da227
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c0063996-cdc5-42d9-bac2-18ef5ae9c736 # Contact Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a7c1133-23c9-47a6-8209-6174dd19e680
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d448521-a924-4134-abc4-03dc5fe0ef6b
        userCondition: null
handle: contactInfo
hasTitleField: false
icon: ''
name: 'Contact Info'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
