color: null
fieldLayouts:
  0d6b6a40-9f39-49a1-ae08-8147ef9dbed1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb90468b-0fd0-451d-aaa5-d3f59bf01b53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d20f603-8807-492c-b939-858d84739f19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6a8e61d4-4a3a-473c-a31e-5bba2449b534 # Contact
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ea55117-e552-4fbf-9af7-55d52d30b011
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 42042a18-6046-4d86-b492-414feae84063
        userCondition: null
handle: contactUrl
hasTitleField: false
icon: ''
name: 'Contact Url'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
