color: null
fieldLayouts:
  104b72c8-744a-4b5d-a1fa-9e516fc6d8dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23a5503e-58a9-4c12-8f04-8111d663df3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ff7e4b2d-13bf-47c1-956a-d9b687cff555 # Card
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cb73dda-f4bd-41d0-9ca1-847a48292bff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1031dc3a-ddfb-4876-b529-f2e5525897e1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccdc2bec-e1cb-44da-b499-7517bd379cf9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5e8a43e-f72a-4654-8f85-6784fae86664
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f5da106-4758-4a32-806f-a95ba43b826b # Sub Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be86f2d0-a212-463e-af04-40be7cce1710
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b4f23ea-db99-4f6d-b632-fa874b3fd2c7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b725ddfa-71d5-44fd-b67b-d2291907d5fd # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 830611e1-552f-4109-b4c9-76e7652ea84c
            userCondition: null
            warning: null
            width: 100
        name: Auxiliary
        uid: e60dae47-a295-42c9-b430-683bd8b3ae71
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Block Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 304e94f7-93a2-48e3-bd92-f72dc6ad2a31
            userCondition: null
          -
            elementCondition: null
            fieldUid: e11f61eb-fec8-4ca1-bdf7-1bc2d00e68e9 # Card Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd2135d5-210d-47a1-9886-8a7ab6e04885
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4daa21a6-7d9e-4652-b72d-4b86d193b8cd # Content Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8113fb25-2e5e-4be0-8e7b-07472c230571
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b639435-9f82-4cfa-9b34-0421722361c9 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93c6feca-b03c-4b84-b24b-272b132ddb98
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 54a3d4c9-582f-4754-8977-4c342ef8a96e # Overlay Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4efe74a1-a2cb-4b22-954b-29c555bdc8f6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55d7d3ae-03a3-4e89-9f46-9ec237b051c7 # Listing Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b90bf3e3-2ad7-468e-9551-3860369f3233
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8520c628-a802-4dac-a4ea-bd88e6785ecb # Per Row Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3dbe92f-57fc-4048-9281-c9b7a4c5fb97
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Content Settings'
            type: craft\fieldlayoutelements\Heading
            uid: e2f143de-781c-4539-b4a6-ef2d650eca7d
            userCondition: null
          -
            elementCondition: null
            fieldUid: f5f3b40a-47d4-42d5-b50a-5e17eae1e600 # Content Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3cde0fb-7184-4e63-a4fa-0bc3f40bb9ff
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e38ac257-70df-4d50-9384-503f2133f772 # Heading Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efc3b830-58ea-4da4-86c5-8eb93ece492a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 0e6d4e36-9f7c-4320-bfad-dcc290f8e135 # Font Weight
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 108b7a6f-5dc7-4842-81fc-e90d16b57ce8
            userCondition: null
            warning: null
            width: 25
        name: Settings
        uid: 340bbd23-b888-4051-83aa-8e2b38e35b73
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 86035a0d-51de-4bb2-b452-4bfc32cfc03e # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9adc9b1-46ff-4e6b-b5f3-56ef259a9b5f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f4be19c5-ac47-4a53-808f-46357722601c # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 599429e7-d739-4ffa-8707-34546ce47f77
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c16118bb-d24d-489d-8c5a-2deabdcd6e16 # Padding Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68e23792-7df5-462c-aee8-009d7cfdc23c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bff0694b-0a96-4afa-ba0e-b4e834e9a153 # Padding Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2c795d9-ffe7-4a85-90a7-1cacb81642ce
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 59855329-2322-4eff-8de5-5ce89790cb6d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: animation
            includeInCards: false
            instructions: null
            label: 'Aniamtion?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a6d400d-7893-4564-842c-15e17845d1e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6a744b5b-ff09-494c-8297-1fe04713b9e0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 1d563f74-0673-4d93-9848-cfbf74332e88 # Animation Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12aef760-26e3-4167-ba70-ccfb92dcbbcd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ed742f3d-8fc4-44e1-b975-1b03cb9ab839 # Animation Easing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6afa463f-c44d-47a0-a64e-6f6897b62e70
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 86da9d1c-79b6-4b38-bfe8-d608e36d610c # Animation Duration
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92e41e76-56b4-45f6-b6ba-52558e255b20
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 703a980f-eab2-4276-a815-17e7b6f5095a # Animation Offset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6922fbc2-e7e9-484d-831e-cebfd135aa5f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7dc70dce-1142-4b7c-8bc2-dcd14e3139b9
            userCondition: null
          -
            elementCondition: null
            fieldUid: 1d563f74-0673-4d93-9848-cfbf74332e88 # Animation Style
            handle: animationStyle2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8eadfb1-1c6e-42d7-8afa-3b21a80b57e8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ed742f3d-8fc4-44e1-b975-1b03cb9ab839 # Animation Easing
            handle: animationEasing2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7de8a102-ac61-4a7a-b363-e07b71a5cdc2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 86da9d1c-79b6-4b38-bfe8-d608e36d610c # Animation Duration
            handle: animationDuration2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce18877d-6d73-433e-bec7-0329e128b4a5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 703a980f-eab2-4276-a815-17e7b6f5095a # Animation Offset
            handle: animationOffset2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93446178-ca79-45f7-9b08-6ed387974206
            userCondition: null
            warning: null
            width: 50
        name: Aniamtion
        uid: dab1c8de-bfc9-415b-9489-a76e66558136
        userCondition: null
handle: dualCards
hasTitleField: false
icon: ''
name: 'Dual Cards'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
