color: null
fieldLayouts:
  2e7e1f48-4c8c-4753-8ef8-3311780e1a74:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 073919a4-ab9d-437d-b635-3dd6a60c49c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: formHeading
            includeInCards: false
            instructions: null
            label: 'Form Heading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1743400f-c01d-4acc-9499-e085313516e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07973944-8eb1-4911-962e-d81e1787b026 # Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d33bd06-f574-4f25-b525-2670b802c361
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Sidebar Content'
            type: craft\fieldlayoutelements\Heading
            uid: 78442d5c-ecb0-485c-b3d4-acdd3b042dc6
            userCondition: null
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: sidebarHeading
            includeInCards: false
            instructions: null
            label: 'Sidebar Heading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 893f0dda-041d-4bbf-88a1-3b9e6556cdcd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c43e81f-f344-4898-bf18-5aff190f9af3 # Contact Info
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbb8bb6d-5bd7-4b18-8718-63006a9d2a89
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 641f0bff-d925-492b-8561-359c294b9f19
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29899b0a-bcc9-4b26-8d23-af169a162a1a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 476ddde4-ba5e-4595-b978-97bf4ba31dd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19e9a5e1-0757-4797-a038-6c5635d42240
            userCondition: null
            warning: null
            width: 100
        name: Auxiliary
        uid: b56dd31e-3ad5-4bc9-82fa-38304a67fb8d
        userCondition: null
handle: form
hasTitleField: false
icon: ''
name: Form
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
