color: null
fieldLayouts:
  d844c440-9514-4d91-b453-b8a676e2d4b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 007171d2-ad72-465b-84f2-4b430a4acb56
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 873433f0-3878-4512-b80a-84e11ace7831 # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4dbbe6f-0ba5-42b0-bd2c-44fa278964fb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c207262-9e8c-49c6-ab4f-1871553d9760
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cad03e6d-8afe-48ed-974d-c98aee5220fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a251325b-13ed-40c8-bcca-027899cb4770
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f5da106-4758-4a32-806f-a95ba43b826b # Sub Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36efdedf-4982-4f72-9df4-bc1573052515
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fd38095-89a4-4c36-a96f-a82ccc4f819c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b725ddfa-71d5-44fd-b67b-d2291907d5fd # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fda83a3f-3f5c-483f-92d7-5301f5631606
            userCondition: null
            warning: null
            width: 100
        name: Auxiliary
        uid: 0f960deb-2ce5-4b2c-9659-b2f14487ac9a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Block Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 24aa6d58-0080-4796-81c2-ea5104d74bc0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 4daa21a6-7d9e-4652-b72d-4b86d193b8cd # Content Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d3deb2c-1526-4ece-aee7-283866cbab8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e835274-c615-428f-bb84-0acaedf10a47 # Gallery Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd947c9b-61b5-4559-8e71-9842abceeab7
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 7e835274-c615-428f-bb84-0acaedf10a47 # Gallery Layout
                  layoutElementUid: cd947c9b-61b5-4559-8e71-9842abceeab7
                  operator: in
                  uid: 6ba15352-5384-494b-96ef-511e2d4fcdf3
                  values:
                    - single
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 55d7d3ae-03a3-4e89-9f46-9ec237b051c7 # Listing Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c04edbc9-b9d4-48af-8bc6-bbbd01f3926f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5b639435-9f82-4cfa-9b34-0421722361c9 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b97400ff-f4f7-4053-8c54-03526c5b0296
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 7e835274-c615-428f-bb84-0acaedf10a47 # Gallery Layout
                  layoutElementUid: cd947c9b-61b5-4559-8e71-9842abceeab7
                  operator: in
                  uid: a5c5dc65-d0a6-430e-b329-31cb48fcb0a1
                  values:
                    - single
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1278138f-e268-4a57-b50e-ad8d14eacb53 # Image Ratio
            handle: null
            includeInCards: false
            instructions: 'Only works if single image gallery option is selected.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92194adc-1a5a-4bc8-90ea-2bffe292d1f1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 7e835274-c615-428f-bb84-0acaedf10a47 # Gallery Layout
                  layoutElementUid: cd947c9b-61b5-4559-8e71-9842abceeab7
                  operator: in
                  uid: dffcc8f2-823c-4d73-8d69-f4fc02870682
                  values:
                    - single
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d5e72f4c-5e9b-4b94-b75c-b4d69e74f1a2 # Per Row Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64f9623c-bb80-49bd-bf55-6d3943895454
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            heading: 'Content Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 9b46905f-f24e-46b6-8ad7-0ef3c2405d06
            userCondition: null
          -
            elementCondition: null
            fieldUid: f5f3b40a-47d4-42d5-b50a-5e17eae1e600 # Content Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3bfc2a6-d566-4b41-addc-8dfa46466e1e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e38ac257-70df-4d50-9384-503f2133f772 # Heading Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6949b284-6b30-4bd0-a93c-b5d760a83cae
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 0e6d4e36-9f7c-4320-bfad-dcc290f8e135 # Font Weight
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeeb1ff2-7a2a-46d6-89ed-534f3e9272db
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 109e85c0-6434-4307-8ad8-de34413241e0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2ba320e0-e879-4969-b03c-211b60735a5a # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd32e136-575d-4daf-9a30-af4d9e9acaef
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: db5f1994-6482-49de-a7dc-985643035717
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 86035a0d-51de-4bb2-b452-4bfc32cfc03e # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e711bc4-2d38-4ead-b829-edde6bffa67e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f4be19c5-ac47-4a53-808f-46357722601c # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a718cec-5c94-45fd-9b1b-6b39826036c0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c16118bb-d24d-489d-8c5a-2deabdcd6e16 # Padding Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ea4fb62-fc0c-444b-ac4b-7e1cbdd4e682
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bff0694b-0a96-4afa-ba0e-b4e834e9a153 # Padding Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4c56101-45bd-4a14-a8d2-6ab4de67c079
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 07cb5b6d-109a-4932-a3d1-f59214cd5fae
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: animation
            includeInCards: false
            instructions: null
            label: 'Animation?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e49856b8-19b2-4e50-a572-67bf0fdbbcfd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Content Animation'
            type: craft\fieldlayoutelements\Heading
            uid: b5507f5d-0ab8-4580-b237-0e9f9427e6b6
            userCondition: null
          -
            elementCondition: null
            fieldUid: 1d563f74-0673-4d93-9848-cfbf74332e88 # Animation Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fb4caff-a4cf-4081-9ff2-aba1e7b78c7d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ed742f3d-8fc4-44e1-b975-1b03cb9ab839 # Animation Easing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ebedf6e-df5e-42d9-af1e-11857f1d7e7f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 86da9d1c-79b6-4b38-bfe8-d608e36d610c # Animation Duration
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09f7d2e6-7322-40b3-ae61-f97f59cf36a8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 703a980f-eab2-4276-a815-17e7b6f5095a # Animation Offset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 709d5eca-39f5-4cd0-a42a-830b099b33d3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Image Animation'
            type: craft\fieldlayoutelements\Heading
            uid: ad9a0c0a-ea08-428e-b8f8-f0941f7a6a29
            userCondition: null
          -
            elementCondition: null
            fieldUid: 1d563f74-0673-4d93-9848-cfbf74332e88 # Animation Style
            handle: animationStyle2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e346edd8-7c57-4a98-9c35-6cffb7209254
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ed742f3d-8fc4-44e1-b975-1b03cb9ab839 # Animation Easing
            handle: animationEasing2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07a5cd32-7369-4170-86d4-98ddb6ccb822
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 86da9d1c-79b6-4b38-bfe8-d608e36d610c # Animation Duration
            handle: animationDuration2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3df925f9-35fd-4b1e-9bb3-a894c42f8772
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 703a980f-eab2-4276-a815-17e7b6f5095a # Animation Offset
            handle: animationOffset2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32d4ee24-1a7e-4eca-83c1-d1440aacc255
            userCondition: null
            warning: null
            width: 50
        name: Animation
        uid: dd44da49-18bf-4453-b21e-685f75f40e65
        userCondition: null
handle: gallery
hasTitleField: false
icon: ''
name: Gallery
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
