color: null
fieldLayouts:
  59ee7a45-d74c-4c2c-89e6-af8000fa39a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb197e14-8584-4aa9-9a4c-0f3232937911
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1cb58e0a-7886-40d7-87eb-ec4149cbc280 # Related Testimonials
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94a85ece-1265-474c-b52d-5027bf4f746d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1c64fc2-eb9b-44d0-82d0-363b76bfcadb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1cc32b3f-8297-426d-a395-8306d849c1f5 # Testimonial Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99f50ff0-7e55-4204-a40b-96119cf9d481
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55d7d3ae-03a3-4e89-9f46-9ec237b051c7 # Listing Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21538220-c78a-4afe-8399-ebfe33fc1b05
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cc5e2abd-42a9-498e-a6f6-d6596c99d2c5 # Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20d46138-edb5-4018-8e7e-ee865e27df8a
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 21ea6231-72a0-49ef-83d7-a1c7b8549b99
        userCondition: null
handle: listingTestimonials
hasTitleField: false
icon: ''
name: 'Listing Testimonials'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
