color: null
fieldLayouts:
  f544ec34-7a4f-4c5f-8463-d8c18f0b2ac8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 43d715e7-f6d5-4624-bebe-45d516b9a826
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b7656e3d-5aea-4dd8-b626-4559b083998b # Related Blog
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e047632-e02b-4c78-837c-4f489869f554
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c2179b4a-5961-47e8-a68f-18d176471710
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc5e2abd-42a9-498e-a6f6-d6596c99d2c5 # Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b38f9661-f2fe-4a31-a117-3ffe14460756
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8404f8a0-0657-4072-9900-4f9c783fed32 # Listing Style 2
            handle: null
            includeInCards: false
            instructions: null
            label: 'Listing Style'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ac750e8-6168-4be9-9d71-6ff755c3df02
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 8404f8a0-0657-4072-9900-4f9c783fed32 # Listing Style 2
                  layoutElementUid: 9ac750e8-6168-4be9-9d71-6ff755c3df02
                  operator: ni
                  uid: 33953821-b199-459a-8153-6c4f7ef0fa06
                  values:
                    - stacked
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d5e72f4c-5e9b-4b94-b75c-b4d69e74f1a2 # Per Row Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bba02f1e-3326-4873-bf24-4ef5cca40e58
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: filter
            includeInCards: false
            instructions: null
            label: 'Filter?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3acbcaf-59a7-4798-8b62-bb8c544f67dd
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: pagination
            includeInCards: false
            instructions: null
            label: 'Pagination?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 655122a8-659b-4978-b38d-d3ae98d70866
            userCondition: null
            warning: null
            width: 25
        name: Settings
        uid: b1e98ca9-2c49-479a-ad7b-ca30b74dd594
        userCondition: null
handle: listingBlog
hasTitleField: false
icon: ''
name: 'Listing Blog'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
