color: null
fieldLayouts:
  e16200e2-d5b9-4f72-867c-d6a73a5ff2a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0290e59-9f08-427a-a359-c5537400d78b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1eaebe24-9727-4d24-969d-6c0a6012f7c5 # Listing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37fe8d71-27c0-40a2-9b07-829220d9ca2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 337e4795-005d-4269-b388-2581487da3b2
        userCondition: null
handle: listing
hasTitleField: false
icon: ''
name: Listing
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
