color: null
fieldLayouts:
  edfeb319-9592-4858-bf8d-9125a0c6b735:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1ae80644-7cca-4b93-af3a-35790218e8c7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c9e70f29-03b1-4160-9e90-2609be52be79 # Related Team
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3378455b-b576-49ce-984e-e27360a8b1b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ffa080d-80bb-4434-8ec5-de919a98c3f6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc5e2abd-42a9-498e-a6f6-d6596c99d2c5 # Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd9af296-fb3b-4c24-991f-a7e1f6bf573e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55d7d3ae-03a3-4e89-9f46-9ec237b051c7 # Listing Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0732b975-9b0b-4f6f-85e9-9fab5b0625ce
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 3628e78b-37a1-44d4-8835-e358e6c5c2b3
        userCondition: null
handle: listingTeam
hasTitleField: false
icon: ''
name: 'Listing Team'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
