color: null
fieldLayouts:
  2e268647-ae7f-455d-9a90-f9ad6ce001ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3f473024-42a7-41b7-b353-c3162f69df49
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 19036f8c-8350-455e-a721-9938e3cf9811 # Related Case Study
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d624309c-5be3-40ff-b2f0-1eafab4406da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2fe7bb59-45a6-45b7-8250-47c3d21b1e9f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c23691fd-0f4a-4576-805e-31effcb2e66b # Case Study Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54bdff6a-8b9d-4b2e-95b1-7c9de5408343
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8404f8a0-0657-4072-9900-4f9c783fed32 # Listing Style 2
            handle: null
            includeInCards: false
            instructions: null
            label: 'Listing Style'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a2bd411-031e-4306-b667-1a798be5c0b7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cc5e2abd-42a9-498e-a6f6-d6596c99d2c5 # Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e94c14e3-faf0-4ae2-aea8-61fb3f3d9053
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 8404f8a0-0657-4072-9900-4f9c783fed32 # Listing Style 2
                  layoutElementUid: 6a2bd411-031e-4306-b667-1a798be5c0b7
                  operator: ni
                  uid: 51b8fece-133c-4cd1-96be-94a3dbaceede
                  values:
                    - stacked
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d5e72f4c-5e9b-4b94-b75c-b4d69e74f1a2 # Per Row Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b06f481-4630-4f14-b15b-fd3ae32aeee0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 8404f8a0-0657-4072-9900-4f9c783fed32 # Listing Style 2
                  layoutElementUid: 6a2bd411-031e-4306-b667-1a798be5c0b7
                  operator: ni
                  uid: 60723907-f7c1-4277-ba20-3ebc61e62c86
                  values:
                    - slider
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: pagination
            includeInCards: false
            instructions: null
            label: 'Pagination?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 421554b6-5781-4df2-8ef5-3356caacd2bf
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: edcebbe3-25a1-447d-83e2-b388048aee64
        userCondition: null
handle: listingCaseStudy
hasTitleField: false
icon: ''
name: 'Listing Case Study'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
