color: null
fieldLayouts:
  53ca72f3-edd3-43f1-8002-7c694b6b486d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6dfa2ee5-f3c7-40ad-ab3f-ed2bbe72dce2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6343b9b3-faa9-4f99-b112-fdec9bd6d770 # Related Client
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 137dd50e-75e2-4a22-a7e4-96e52c35b7a2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e362838f-41e0-4d8a-ab25-e22849ad8306
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d5e72f4c-5e9b-4b94-b75c-b4d69e74f1a2 # Per Row Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 476c22f8-7d7b-47df-9db2-b0cfdb0a0562
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cc5e2abd-42a9-498e-a6f6-d6596c99d2c5 # Limit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3900ae3e-4081-4cb2-ab24-286380430f02
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55d7d3ae-03a3-4e89-9f46-9ec237b051c7 # Listing Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c46847c2-69f0-432e-a9f1-4f3fcd1f9faf
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: showBorder
            includeInCards: false
            instructions: null
            label: 'Show Border?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05144943-4677-480c-ab0a-b5bd9abbae3b
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 8cc99741-1bdc-43c4-842b-f86e84a1c955
        userCondition: null
handle: listingClient
hasTitleField: false
icon: ''
name: 'Listing Client'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
