color: null
fieldLayouts:
  e2b8cbdc-0236-4eb8-981e-7e5d63c50bf2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e83cff44-d210-45c7-b758-ae21374b3b2d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6df5443-44eb-4d91-9232-62ccf21b3e83 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eced19e-013d-406b-a22f-d0a6070435cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8924f8be-b7ee-44cf-991c-9fc458096173 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 484b3f47-0d1f-4be9-8425-ead2d9b15fb7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e1e17b96-6cbb-4320-99d9-8e5f1a23fe2d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: overrideCta
            includeInCards: false
            instructions: null
            label: 'Override CTA'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4b69fef-4d4f-40df-b861-3651a7f36ee1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
                  layoutElementUid: d4b69fef-4d4f-40df-b861-3651a7f36ee1
                  uid: 0964f473-a047-4653-9ff2-ae942dbbf0d5
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 3103da10-e23c-4bc6-8d50-79ecfca1013e # Call To Action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e990415d-12e1-47b2-aa16-ba737e658069
            userCondition: null
            warning: null
            width: 50
        name: 'Override CTA'
        uid: ca342092-0328-4286-8d8e-76c050935658
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b3c80522-1b2a-44ca-954e-be2e2544ebd9 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44f689be-7dd8-4b52-be2e-251e7166e840
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 5621bb3d-3953-4aee-845f-1dbfb6ea8972
        userCondition: null
handle: pages
hasTitleField: true
icon: ''
name: Pages
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
