color: null
fieldLayouts:
  56200af1-9bd1-4afb-a489-fb030dd7c8f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a5c41cf-ad4d-45e4-8a55-baa22c27abcf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a7720afc-ed4d-4b75-bfdd-b504f6f7a9a4 # Quote
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ed9743f-d3d7-4d09-9dff-040426c5c0e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: authorName
            includeInCards: false
            instructions: null
            label: 'Author Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 251611dd-cba3-47d4-8b82-88042f1ec74c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: designation
            includeInCards: false
            instructions: null
            label: Designation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c8c6056-a7bf-4c21-9e45-a16481e69596
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6a21dc96-cb6b-46f2-b9da-7ee9ebc1d3f1
        userCondition: null
handle: quote
hasTitleField: false
icon: quote-right
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
