color: null
fieldLayouts:
  ec6e3cc4-2d56-4c26-8cf7-18bc3fcbc7bf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6399e08b-db9a-4f17-93c1-148de80b0265
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05af4b17-93ed-4027-a039-96c368e5b585 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4c345f2-cec8-4371-ba6a-98869aded4b9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1dd3a6ac-82ac-4ebb-8097-c66521644b0b # Team Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0607f89f-fe73-48da-a7a6-87de994e47ab
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: designation
            includeInCards: false
            instructions: null
            label: Designation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c7d633b-2201-42fb-bfb4-5eab3e3757a2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d3586ea4-5f88-4f21-ad96-2802fc795b6b
        userCondition: null
handle: team
hasTitleField: true
icon: ''
name: Team
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
