color: null
fieldLayouts:
  7d1a2815-b2bf-4607-8f3e-137e18698033:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8fbca59f-41d7-42b2-9ba4-ff17e8f84593
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05af4b17-93ed-4027-a039-96c368e5b585 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e670e0c-255d-4f09-837b-354aa5c6a9b1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6343b9b3-faa9-4f99-b112-fdec9bd6d770 # Related Client
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d08dadc-aed4-4fb2-90ca-514c1531a91d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a7720afc-ed4d-4b75-bfdd-b504f6f7a9a4 # Quote
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f31e5db-79d5-4261-8228-277fd8fe7b5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: clientName
            includeInCards: false
            instructions: null
            label: Name
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 533b3b16-19e2-4562-ad30-753a274da464
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: designation
            includeInCards: false
            instructions: null
            label: Designation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c88b06a-128a-498f-a01a-89341edf4214
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: ff4e0008-28a6-4a1c-b005-e1fe3f2962c9
        userCondition: null
handle: testimonial
hasTitleField: true
icon: ''
name: Testimonial
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
