color: null
fieldLayouts:
  8561f758-1c64-42c5-8556-d59244fceda3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fe0ee4b1-c3f4-410f-b0ee-412b6ca10c83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b6c930d-d00e-4a6c-9e5e-734464c5066a # Simple Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ba18412-7563-46d9-94c5-f8113f8fba4e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1a5697b1-8be8-4023-b6bc-5e00edb34810
        userCondition: null
handle: textCard
hasTitleField: false
icon: ''
name: 'Text Card'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
