color: null
fieldLayouts:
  45d25b1a-cbb2-43a4-8571-1b90929dec28:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 430b5e45-eb0a-4079-b979-2562f13d7258
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f78ca44b-dc07-47fe-934c-9bba67bd7b58
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8068b4f8-14d3-4989-9beb-01e047f658c5 # Script Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6497b5c0-8e54-4298-b637-fe3d3884d869
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 07f716e2-b6e5-4aaa-aa76-1a49c9929017 # Light switch
            handle: addOnlyInProduction
            includeInCards: false
            instructions: null
            label: 'Add only in Production?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4967d4a-5d1b-45fa-9125-b945a1089cd4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e3651006-9863-4745-9226-557c2608dee0 # Script Files
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56e500f2-9bf8-4eb4-a137-26371afd0f72
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4de72344-704b-4799-abfa-de28d92a6c41 # Javascript Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a89a687-cc5f-4450-9144-c14ce45ef14c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a083fcfb-b4ce-402b-a0bb-e03d70ddf2ec # HTML Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7df1c6e-3ea7-4fb9-9723-f3761209e2e7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d3e0f439-d67d-4424-8779-a9d74374dc49
        userCondition: null
handle: trackingScripts
hasTitleField: false
icon: ''
name: 'Tracking Scripts'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
