color: null
fieldLayouts:
  bafbefca-f2ef-49a8-8750-ea49a51c158d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ca87baa-08f7-4d95-8d20-c9f87b7cc05d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e3c2782-28f2-47a9-8b70-cd972393e4d3 # Two Columns
            handle: null
            includeInCards: false
            instructions: null
            label: Column
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d77fed76-39a8-4fad-88ea-56e4853ddb63
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 16535215-e7ab-4d82-a647-aaea3a93ee9e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f7a03cc1-a16d-4c45-9dfd-c869032b4453 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a90d556-d21f-4c65-bb64-f7bb628dc873
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c9e12a1-ad97-4d5d-abb9-66c3617ec7d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f5da106-4758-4a32-806f-a95ba43b826b # Sub Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84f22929-360c-49e0-ba55-0acf4f4c8640
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 810e4a88-d509-4197-a102-dace8ccb0db5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9941aee1-da63-4d40-91fd-54046376a0a3
            userCondition: null
          -
            elementCondition: null
            fieldUid: b725ddfa-71d5-44fd-b67b-d2291907d5fd # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d582a1e2-8696-4da3-ac95-698efb97f057
            userCondition: null
            warning: null
            width: 100
        name: Auxiliary
        uid: 04935208-9d00-45ac-a40b-b4fda33f3e13
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Block Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 8e338b5f-de4a-4de9-848b-4c366814cf12
            userCondition: null
          -
            elementCondition: null
            fieldUid: 4daa21a6-7d9e-4652-b72d-4b86d193b8cd # Content Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46951625-f8a3-4070-a5d8-c99a5ab59784
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: e084ec80-7142-4f11-95cc-afaccaed2cf6 # Column Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f9a5a38-6af9-42b0-9dc8-047a6606de2e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5b639435-9f82-4cfa-9b34-0421722361c9 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a8e8ec1-f9b0-45b2-be42-066c0c716f32
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 67cd1597-672e-4ec8-a388-c982f3f2291f # Two Column Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f634912a-34b4-4879-b386-d719ba69f964
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Content Settings'
            type: craft\fieldlayoutelements\Heading
            uid: fe3e7373-6357-4817-8b4f-887c6f2fcc8d
            userCondition: null
          -
            elementCondition: null
            fieldUid: f5f3b40a-47d4-42d5-b50a-5e17eae1e600 # Content Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f8044dd-c29c-493c-ad6c-4b88899e84f4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e38ac257-70df-4d50-9384-503f2133f772 # Heading Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4d7e1e2-13bb-46ac-9451-c0c37c43dcc4
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 0e6d4e36-9f7c-4320-bfad-dcc290f8e135 # Font Weight
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38a14ba7-34b1-4bb0-a62f-ac94c323ad79
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c6e9705b-fbbf-4e96-8c20-df4d94b77be0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2ba320e0-e879-4969-b03c-211b60735a5a # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d2ad9bc-21fa-48e5-85bd-09eec1a8495c
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: e9a410e0-9e73-427c-a3f8-f1249e2dc656
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 86035a0d-51de-4bb2-b452-4bfc32cfc03e # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51ccb0b7-e854-4a32-9eb0-faf503c0033d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f4be19c5-ac47-4a53-808f-46357722601c # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f798790-3bc2-461f-b7fd-733aefb83ad5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c16118bb-d24d-489d-8c5a-2deabdcd6e16 # Padding Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fefa0846-82f4-46e0-ad07-a88904c234c8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bff0694b-0a96-4afa-ba0e-b4e834e9a153 # Padding Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1843c250-3477-48f9-bf9c-844584b90474
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 0c980b75-c666-43a6-9ec9-5a56a58f6876
        userCondition: null
handle: twoColumns
hasTitleField: false
icon: ''
name: 'Two Columns'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
