altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5aed529d-2370-4f3c-9df1-d6a32d8c4539:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bf6487a5-08b2-4799-9582-aece0a392d76
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2fc69811-bd2f-4b7c-a94f-e8143a537790
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: ''
