altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  92774858-6df2-42d8-9239-09a27645d539:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4c9d7c20-f692-449b-b5e2-63f34d8d9c4c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c82c3876-4f17-4fa2-9aad-14c4efa843f9
        userCondition: null
fs: videos
handle: videos
name: Videos
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: ''
