columnSuffix: null
handle: animationStyle
instructions: null
name: 'Animation Style'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/animationStyle.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
