columnSuffix: null
handle: animationDuration
instructions: null
name: 'Animation Duration'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/animationDuration.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
