columnSuffix: null
handle: animationEasing
instructions: null
name: 'Animation Easing'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/animationEasing.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
