columnSuffix: null
handle: animationOffset
instructions: null
name: 'Animation Offset'
searchable: false
settings:
  cachedOptions: true
  element: null
  genError: ''
  json: ''
  template: _/sdf/animationOffset.json
  templateData: ''
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
