columnSuffix: null
handle: animationOffset
instructions: null
name: 'Animation Offset'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/animationOffset.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
