columnSuffix: null
handle: backgroundColor
instructions: null
name: 'Background Color'
searchable: false
settings:
  default: null
  palette: 'Background Color'
  setRandom: false
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
