columnSuffix: null
handle: bannerHeight
instructions: null
name: 'Banner Height'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/bannerHeight.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
