columnSuffix: null
handle: buttonType
instructions: null
name: 'Button Type'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/buttonType.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
