columnSuffix: null
handle: callToAction
instructions: null
name: 'Call To Action'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Call To Action'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:cb57046f-f051-4150-917b-97450a183417' # Call To Action
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
