columnSuffix: null
handle: columnAlignment
instructions: null
name: 'Column Alignment'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/columnAlignment.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
