columnSuffix: null
handle: contactInfo
instructions: null
name: 'Contact Info'
searchable: false
settings:
  createButtonLabel: 'Contact Info'
  entryTypes:
    - 32f5e2ff-781a-4e09-8347-1808fb9a7bb2 # Contact Info
  includeTableView: false
  maxEntries: 3
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
