columnSuffix: null
handle: contactCards
instructions: null
name: 'Contact Cards'
searchable: false
settings:
  createButtonLabel: Card
  entryTypes:
    - 72d439b0-45ce-4aaa-94ac-cdda734b4b5a # Text
    - 12eaafb7-f335-4296-9610-453f6f68c8bb # Contact Url
    - d5375257-05b7-4c6e-b808-81ca62e56f9f # Contact Social Links
  includeTableView: false
  maxEntries: 2
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
