columnSuffix: null
handle: fontWeight
instructions: null
name: 'Font Weight'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/fontWeight.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
