columnSuffix: null
handle: headingSize
instructions: null
name: 'Heading Size'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/headingSize.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
