columnSuffix: null
handle: hero
instructions: null
name: Hero
searchable: false
settings:
  createButtonLabel: Hero
  entryTypes:
    - 4cf27aa9-e6b0-48e4-a844-bf76258f6101 # Full
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
