columnSuffix: null
handle: htmlCode
instructions: null
name: 'HTML Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: '<div>My HTML content goes here...</div>'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
