columnSuffix: null
handle: iconPosition
instructions: null
name: 'Icon Position'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/iconPosition.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
