columnSuffix: null
handle: imageRatio
instructions: null
name: 'Image Ratio'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/imageRatio.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
