columnSuffix: null
handle: marginTop
instructions: null
name: 'Margin Top'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/spacing.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
