columnSuffix: null
handle: paddingTop
instructions: null
name: 'Padding Top'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/spacing.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
