columnSuffix: null
handle: paddingBottom
instructions: null
name: 'Padding Bottom'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/spacing.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
