columnSuffix: null
handle: pageBuilder
instructions: null
name: 'Page Builder'
searchable: false
settings:
  createButtonLabel: 'Page Builder'
  entryTypes:
    - aed4b3a7-3590-400d-beca-837fb987570a # Basic Content
    - ad85443f-75fc-45e3-9a29-4592254d416f # Image
    - effa59c4-035a-4910-bf8c-30996bff8047 # Gallery
    - 2d5c34d8-b71f-4777-a3d6-50cb6a4a5402 # Multimedia
    - a7eded6e-c5d3-4099-bb5b-7545b0332f49 # Listing
    - 4d8649f4-2cd8-4a36-9eaf-2251ec44112c # Form
    - 832bf49f-111f-4aea-acea-c39597785d33 # Call To Action
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
