columnSuffix: null
handle: patternBackgroundColor
instructions: null
name: 'Pattern Background Color'
searchable: false
settings:
  default: null
  palette: 'Pattern Color'
  setRandom: false
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
