columnSuffix: null
handle: perRowLimit2
instructions: null
name: 'Per Row Limit'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/perRowLimit2.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
