columnSuffix: null
handle: scriptPosition
instructions: null
name: 'Script Position'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/scriptPosition.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
