columnSuffix: null
handle: scriptPosition
instructions: null
name: 'Script Position'
searchable: false
settings:
  cachedOptions: true
  element: null
  genError: ''
  json: ''
  template: _/sdf/scriptPosition.json
  templateData: ''
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
