columnSuffix: null
handle: twoColumns
instructions: null
name: 'Two Columns'
searchable: false
settings:
  createButtonLabel: Columns
  entryTypes:
    - c8a67f3a-f81d-4fc4-a335-3817d4c32eff # Two Column
  includeTableView: false
  maxEntries: 2
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
