columnSuffix: null
handle: twoColumnLayout
instructions: null
name: 'Two Column Layout'
searchable: false
settings:
  cachedOptions: true
  template: _/sdf/twoColumnLayout.json
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SuperDynamicDropdownField
