dateModified: 1713849970
email:
  fromEmail: n.williams@userfusion.com
  fromName: Userfusion
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: '@webroot/uploads/transforms'
    type: craft\fs\Local
    url: '@web/uploads/transforms'
  videos:
    hasUrls: true
    name: Videos
    settings:
      path: '@webroot/uploads/videos'
    type: craft\fs\Local
    url: '@web/uploads/videos'
meta:
  __names__:
    0e6d4e36-9f7c-4320-bfad-dcc290f8e135: 'Font Weight' # Font Weight
    0f5da106-4758-4a32-806f-a95ba43b826b: 'Sub Heading' # Sub Heading
    0fb4612a-f62e-4f17-a4c0-d4bb9c731e39: 'Button Color' # Button Color
    1ac41e27-14a7-47d4-a7a3-ab64f8959ead: Solid # Solid
    1d563f74-0673-4d93-9848-cfbf74332e88: 'Animation Style' # Animation Style
    1eaebe24-9727-4d24-969d-6c0a6012f7c5: Listing # Listing
    1fa0a156-5d07-4afa-a05a-7f48cebc4c97: Client # Client
    2ba320e0-e879-4969-b03c-211b60735a5a: 'Section ID' # Section ID
    3f060ced-9de9-4e6c-ada9-05cddd5d7c03: Testimonial # Testimonial
    3f94dff8-7848-41bd-bc80-03e884e498a2: Team # Team
    4a0c1fbc-a84a-4308-8167-ed452f56d3b7: 'Contact Form' # Contact Form
    4acc89ab-5d9f-4ea0-a6e1-ba658f8c84d5: 'Button Type' # Button Type
    04addcc4-19dd-4fcc-bef4-b4877e862f6b: Video # Video
    4b8f956e-112a-40a9-a343-78fea17f34cc: 'Tracking Scripts' # Tracking Scripts
    4cf27aa9-e6b0-48e4-a844-bf76258f6101: Full # Full
    4daa21a6-7d9e-4652-b72d-4b86d193b8cd: 'Content Width' # Content Width
    4de72344-704b-4799-abfa-de28d92a6c41: 'Javascript Code' # Javascript Code
    05af4b17-93ed-4027-a039-96c368e5b585: Image # Image
    5b639435-9f82-4cfa-9b34-0421722361c9: 'Background Color' # Background Color
    5bdbc0ac-c142-4128-a741-e438819f43c5: Userfusion # Userfusion
    5c2557f5-9953-495f-98c5-6e03acb0161b: Images # Images
    5f91fed7-8dbd-476c-8ff5-a06bc3edde90: 'Social Links' # Social Links
    06c080b4-85ef-4bf1-b169-562706f7d127: 'Pattern Background Color' # Pattern Background Color
    7c1471a7-a014-4b8f-8e10-1d6064ca6ebd: Team # Team
    7c8987af-e9f1-42e8-930e-4a16028b925d: Button # Button
    7ef67d6e-85ac-42a0-a25d-e7b1c064b81a: Client # Client
    07f716e2-b6e5-4aaa-aa76-1a49c9929017: 'Light switch' # Light switch
    8bdd6695-676c-438d-8cd2-caa3a8940ccb: Full # Full
    8c84eddd-0a33-4f51-a9f8-8c5ff353066d: 'Banner Height' # Banner Height
    009ed4ac-c86b-4fc7-9918-9bd7b4f8157d: Header # Header
    19cc1136-5d7a-45af-a877-b34cbec39f80: 'Listing Team' # Listing Team
    20c4d3d9-29f1-46b9-a578-de6425807cb3: Footer # Footer
    22ffe5d1-c3ff-49ba-8ed8-2ef903d94c54: Userfusion # Userfusion
    54a3d4c9-582f-4754-8977-4c342ef8a96e: 'Overlay Opacity' # Overlay Opacity
    67cc7823-2e87-4d16-bb9f-38b94b68f956: 'Tracking Scripts' # Tracking Scripts
    72d416e1-852e-4aef-b204-c23f104c80c8: Videos # Videos
    83b30345-cc30-4e25-a5f6-5de8adbe8265: Custom # Custom
    86da9d1c-79b6-4b38-bfe8-d608e36d610c: 'Animation Duration' # Animation Duration
    89eb44c8-5d3c-4643-b7e4-310a10612797: Brands # Brands
    91c83f59-fe79-4767-b5d1-f236d7a4e02f: 'Social Link' # Social Link
    93edb1b2-0669-4ae4-a9e7-0e5f4826507a: Regular # Regular
    134a2c99-8e12-4d05-b077-5957f5e835ce: 'Social Links' # Social Links
    0423d9a0-74e7-4a3d-afc5-a78d494caab4: Navigation # Navigation
    703a980f-eab2-4276-a815-17e7b6f5095a: 'Animation Offset' # Animation Offset
    1015ffe6-b7bf-4676-a048-e34055507b5a: Image # Image
    1568efd7-9ad7-471e-ac94-2e679fc981b1: Pages # Pages
    3745cb40-58d5-44cc-9ce5-9339f438f411: Icon # Icon
    4998b347-a2ba-4814-8789-53adb5d61a41: Text # Text
    5816eb09-d316-4d3a-ac94-403833383582: 'Case study' # Case study
    6343b9b3-faa9-4f99-b112-fdec9bd6d770: 'Related Client' # Related Client
    8068b4f8-14d3-4989-9beb-01e047f658c5: 'Script Position' # Script Position
    8924f8be-b7ee-44cf-991c-9fc458096173: 'Page Builder' # Page Builder
    025101ef-e8fd-4542-bd7f-d5d127b6789f: 'Tracking Scripts' # Tracking Scripts
    86035a0d-51de-4bb2-b452-4bfc32cfc03e: 'Margin Top' # Margin Top
    873433f0-3878-4512-b80a-84e11ace7831: Images # Images
    07973944-8eb1-4911-962e-d81e1787b026: Form # Form
    a083fcfb-b4ce-402b-a0bb-e03d70ddf2ec: 'HTML Code' # HTML Code
    a7eded6e-c5d3-4099-bb5b-7545b0332f49: Listing # Listing
    a7720afc-ed4d-4b75-bfdd-b504f6f7a9a4: Quote # Quote
    aed4b3a7-3590-400d-beca-837fb987570a: 'Basic Content' # Basic Content
    b3c80522-1b2a-44ca-954e-be2e2544ebd9: SEO # SEO
    b7febf1c-f446-4af6-a112-a27ec4194078: 'Case studies' # Case studies
    b266d78b-963a-4c95-a2c8-3dadd5595399: Telephone # Telephone
    b725ddfa-71d5-44fd-b67b-d2291907d5fd: Buttons # Buttons
    b1245063-e2a0-4567-8d38-0324ca0eba13: 'Joining Date' # Joining Date
    b7524683-0af1-4bdf-b6f5-e4e80993fbbe: 'Banner Card' # Banner Card
    bff0694b-0a96-4afa-ba0e-b4e834e9a153: 'Padding Bottom' # Padding Bottom
    c729cee4-a2ec-48ef-8053-907b01d1a630: Cards # Cards
    c16118bb-d24d-489d-8c5a-2deabdcd6e16: 'Padding Top' # Padding Top
    cafc15ff-e95d-499e-ab60-3cc42608bc25: New # New
    cf5012cf-d02e-4ac7-98d1-891c12d25777: Button # Button
    d2ce1189-64b3-48a5-8648-327f21b04a5c: Pages # Pages
    d5b54786-d550-43a6-bc46-0e9b8edbae51: Simple # Simple
    d5e72f4c-5e9b-4b94-b75c-b4d69e74f1a2: 'Per Row Limit' # Per Row Limit
    e38ac257-70df-4d50-9384-503f2133f772: 'Heading Size' # Heading Size
    e24737b0-c5aa-4f05-9fb5-fc42d7f31bb0: 'Icon Position' # Icon Position
    e3651006-9863-4745-9226-557c2608dee0: 'Script Files' # Script Files
    ec70c780-286c-4027-8904-ecdb25e3e1c1: Heading # Heading
    ed742f3d-8fc4-44e1-b975-1b03cb9ab839: 'Animation Easing' # Animation Easing
    effa59c4-035a-4910-bf8c-30996bff8047: Logos # Logos
    f0abdae9-c7c1-4963-b95f-474183ac0b20: Testimonial # Testimonial
    f4be19c5-ac47-4a53-808f-46357722601c: 'Margin Bottom' # Margin Bottom
    f5f3b40a-47d4-42d5-b50a-5e17eae1e600: 'Content Alignment' # Content Alignment
    f6df5443-44eb-4d91-9232-62ccf21b3e83: Hero # Hero
    f7a03cc1-a16d-4c45-9dfd-c869032b4453: Eyebrow # Eyebrow
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: J6V10JGXF98U0VGG1OA4JILV
    schemaVersion: 5.0.0.4
  buttonbox:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.3
  craft-range-slider:
    edition: standard
    enabled: true
    licenseKey: 42J2EHB9ON3YAOQDWZSTC1DP
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: NU5DKSGXHK7BA1FCMGWNA4AV
    schemaVersion: 3.4.3
  hyper:
    edition: standard
    enabled: true
    licenseKey: SMSGRUCG3VV4OBI6WSC2TSIX
    schemaVersion: 1.0.0
  icon-picker:
    edition: standard
    enabled: true
    licenseKey: UUSPRFKUXA3HP4ZFB95IN8VI
    schemaVersion: 1.2.3
    settings:
      enableCache: true
      iconItemSize: 32
      iconItemSizeLarge: 40
      iconItemWrapperSize: 56
      iconItemWrapperSizeLarge: 72
      iconSetsPath: '@webroot/icons/'
      iconSetsUrl: '@web/icons/'
      redactorFieldHandle: ''
  imager-x:
    edition: pro
    enabled: true
    licenseKey: GGL06FJ2I82W5UPDNWY8WXEL
    schemaVersion: 4.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: F2B5O0X9MYHV941V3SAP806S
    schemaVersion: 2.1.0
  neo:
    edition: standard
    enabled: true
    licenseKey: ATG0IVUNU15K92BAROSV55RF
    schemaVersion: 5.0.0.1
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  seomatic:
    edition: standard
    enabled: true
    licenseKey: VEOYNRVPT3AZRQIEIGG9OI5Q
    schemaVersion: 3.0.12
  super-dynamic-fields:
    edition: standard
    enabled: true
    licenseKey: 2I944PAYO1BQGRPP6ACH0DDH
    schemaVersion: 5.0.1
  twig-perversion:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Userfusion
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
