fieldLayouts:
  7c867b4e-acbc-4f2a-94ca-5efd88be0f17:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T12:19:41+00:00'
            elementCondition: null
            fieldUid: 3103da10-e23c-4bc6-8d50-79ecfca1013e # Call To Action
            handle: null
            includeInCards: false
            instructions: null
            label: 'Call To Action (Pages)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83ee2171-3038-40a1-a147-e42e488d24d0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-19T12:22:11+00:00'
            elementCondition: null
            fieldUid: 3103da10-e23c-4bc6-8d50-79ecfca1013e # Call To Action
            handle: callToAction2
            includeInCards: false
            instructions: null
            label: 'Call To Action (Case Study) '
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3ac5ff3-e206-4e46-87a5-369f0dea9344
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 3c8944db-77e1-4a0c-ad53-40c9b9a7769a
        userCondition: null
handle: callToAction
name: 'Call To Action'
sortOrder: 5
