fieldLayouts:
  904c23b1-046d-4f65-854e-bdace097890a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T07:05:16+00:00'
            elementCondition: null
            fieldUid: 05af4b17-93ed-4027-a039-96c368e5b585 # Image
            handle: logo
            includeInCards: false
            instructions: null
            label: Logo
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f571e06-58fe-48d0-bd15-9b86116fb162
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-19T07:09:08+00:00'
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: copyrightDescription
            includeInCards: false
            instructions: null
            label: 'Copyright Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6a7021c-9b91-46b1-b992-7fc9d23c4e0d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-19T07:05:16+00:00'
            elementCondition: null
            fieldUid: 0423d9a0-74e7-4a3d-afc5-a78d494caab4 # Navigation
            handle: null
            includeInCards: false
            instructions: null
            label: 'Footer navigation'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd2f5751-0f17-4e1c-83a4-1c468aae9d44
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T07:05:16+00:00'
            elementCondition: null
            fieldUid: ec70c780-286c-4027-8904-ecdb25e3e1c1 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: 'Newsletter Heading'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a503867-9b86-4a9c-b90b-6f7f3ac19292
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T07:05:16+00:00'
            elementCondition: null
            fieldUid: 4998b347-a2ba-4814-8789-53adb5d61a41 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Newsletter Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd7cdb66-9941-45fd-9de1-59ce4708dece
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T07:05:16+00:00'
            elementCondition: null
            fieldUid: 07973944-8eb1-4911-962e-d81e1787b026 # Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27e5b4e6-d87f-4adb-8174-821cd0a5364e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2b704050-9542-4380-bc3a-e1b51f955bac
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
