fieldLayouts:
  26e7a719-a615-4482-b1f4-dca1edca930e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 025101ef-e8fd-4542-bd7f-d5d127b6789f # Tracking Scripts
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1db9bbcf-c1db-42c4-801c-32b248ef808b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 49fb7fdf-d849-423c-9442-17e75b6744c0
        userCondition: null
handle: trackingScripts
name: 'Tracking Scripts'
sortOrder: 3
