defaultPlacement: end
enableVersioning: true
entryTypes:
  - 292523b0-bad0-4ce1-9542-3fe9faffcd40 # Blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5bdbc0ac-c142-4128-a741-e438819f43c5: # Userfusion
    enabledByDefault: true
    hasUrls: true
    template: _pages/blog/entry.twig
    uriFormat: 'blog/{slug}'
type: channel
