defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3f94dff8-7848-41bd-bc80-03e884e498a2 # Team
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5bdbc0ac-c142-4128-a741-e438819f43c5: # Userfusion
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
