defaultPlacement: end
enableVersioning: true
entryTypes:
  - f0abdae9-c7c1-4963-b95f-474183ac0b20 # Testimonial
handle: testimonial
maxAuthors: 1
name: Testimonial
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5bdbc0ac-c142-4128-a741-e438819f43c5: # Userfusion
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
